import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  BorderStyle,
} from "docx";
import type { RoadmapResponse } from "@/types";

/**
 * Generate a formatted .docx Word document from a RoadmapResponse.
 * Returns a Buffer ready to be sent as a file download.
 */
export async function generateRoadmapDocx(roadmap: RoadmapResponse): Promise<Buffer> {
  const date = new Date(roadmap.generatedAt).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const children: Paragraph[] = [
    // Document title
    new Paragraph({
      text: `Client Roadmap: ${roadmap.clientName}`,
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 },
    }),

    // Generated date
    new Paragraph({
      children: [
        new TextRun({
          text: `Generated by IBM Sales Guidance Tool · ${date}`,
          color: "888888",
          size: 20,
        }),
      ],
      alignment: AlignmentType.CENTER,
      spacing: { after: 600 },
    }),

    // Divider
    new Paragraph({
      border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: "0F62FE" } },
      spacing: { after: 400 },
    }),
  ];

  // Add each section
  for (const section of roadmap.sections) {
    // Section heading
    children.push(
      new Paragraph({
        text: section.title,
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 400, after: 160 },
      })
    );

    // Section content — split on newlines to preserve paragraph breaks
    const paragraphs = section.content
      .split(/\n{2,}/)
      .map((p) => p.trim())
      .filter(Boolean);

    for (const para of paragraphs) {
      // Handle markdown bold (**text**) — strip for now, plain text output
      const cleanText = para.replace(/\*\*(.*?)\*\*/g, "$1").replace(/\*(.*?)\*/g, "$1");

      children.push(
        new Paragraph({
          children: [new TextRun({ text: cleanText, size: 22 })],
          spacing: { after: 160 },
        })
      );
    }
  }

  // Footer note
  children.push(
    new Paragraph({
      border: { top: { style: BorderStyle.SINGLE, size: 4, color: "CCCCCC" } },
      spacing: { before: 600 },
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: "Generated by IBM Sales Guidance Tool · Powered by IBM Watson Assistant & AskSales",
          color: "888888",
          size: 18,
          italics: true,
        }),
      ],
      alignment: AlignmentType.CENTER,
    })
  );

  const doc = new Document({
    sections: [{ children }],
  });

  return Packer.toBuffer(doc);
}
